# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
	rk3588-i2c0-m1.dtbo \
	rk3588-i2c1-m0.dtbo \
	rk3588-i2c2-m4.dtbo \
	rk3588-i2c3-m1.dtbo \
	rk3588-i2c4-m3.dtbo \
	rk3588-i2c6-m3.dtbo \
	rk3588-i2c7-m3.dtbo \
	rk3588-i2c8-m2.dtbo \
	rk3588-i2c8-m4.dtbo \
	rk3588-pwm0-m2.dtbo \
	rk3588-pwm1-m2.dtbo \
	rk3588-pwm2-m1.dtbo \
	rk3588-pwm3-m1.dtbo \
	rk3588-pwm3-m3.dtbo \
	rk3588-pwm5-m2.dtbo \
	rk3588-pwm6-m2.dtbo \
	rk3588-pwm7-m3.dtbo \
	rk3588-pwm8-m0.dtbo \
	rk3588-pwm11-m1.dtbo \
	rk3588-pwm12-m0.dtbo \
	rk3588-pwm13-m0.dtbo \
	rk3588-pwm13-m2.dtbo \
	rk3588-pwm14-m0.dtbo \
	rk3588-pwm14-m1.dtbo \
	rk3588-pwm14-m2.dtbo \
	rk3588-pwm15-m0.dtbo \
	rk3588-pwm15-m1.dtbo \
	rk3588-pwm15-m3.dtbo \
	rk3588-spi0-m2-cs0-spidev.dtbo \
	rk3588-spi0-m2-cs1-spidev.dtbo \
	rk3588-spi1-m1-cs0-spidev.dtbo \
	rk3588-spi1-m1-cs1-spidev.dtbo \
	rk3588-spi4-m2-cs0-spidev.dtbo \
	rk3588-uart2-m0.dtbo \
	rk3588-uart2-m2.dtbo \
	rk3588-uart3-m1.dtbo \
	rk3588-uart4-m2.dtbo \
	rk3588-uart6-m1.dtbo \
	rk3588-uart7-m1-ctsn-rtsn.dtbo \
	rk3588-uart7-m1.dtbo \
	rk3588-uart7-m2.dtbo \
	rk3588-uart8-m0.dtbo \
	rock-4-okdo-5mp-camera.dtbo \
	rock-4-rpi-camera-v1p3.dtbo \
	rock-4-rpi-camera-v2.dtbo \
	rock-4ab-raspi-7inch-touchscreen.dtbo \
	rock-4c-plus-raspi-7inch-touchscreen.dtbo \
	rock-4c-plus-radxa-display-8hd.dtbo \
	rock-4c-plus-radxa-display-10hd.dtbo \
	rock-4c-plus-radxa-display-10fhd.dtbo \
	rock-5a-hdmi-8k.dtbo \
	rock-5a-i2c5-rtc-hym8563.dtbo \
	rock-5a-radxa-camera-4k.dtbo \
	rock-5a-radxa-display-8hd.dtbo \
	rock-5a-radxa-display-10hd.dtbo \
	rock-5a-spi-nor-flash.dtbo \
	rock-5a-usb-otg.dtbo \
	rock-5b-hdmi1-8k.dtbo \
	rock-5b-hdmi2-8k.dtbo \
	rock-5b-pd-max-voltage-12v.dtbo \
	rock-5b-radxa-display-8hd.dtbo \
	rock-5b-radxa-display-10hd.dtbo \
	rock-5b-rpi-camera-v2.dtbo \
	rock-5b-radxa-camera-4k.dtbo \
	rock-5b-sata.dtbo \
	radxa-cm3s-io-csi1-rpi-camera-v2.dtbo \
	radxa-cm3s-io-csi1-okdo-5mp-camera.dtbo \
	radxa-cm3s-io-csi0-rpi-camera-v2.dtbo \
	radxa-cm3s-io-csi0-okdo-5mp-camera.dtbo \
	radxa-cm3-sodimm-io-raspberrypi-7inch-touchscreen.dtbo \
	radxa-cm3-sodimm-io-radxa-display-8hd.dtbo \
	radxa-cm3-rpi-cm4-io-disable-emc2301.dtbo \
	radxa-cm3-rpi-cm4-camera-v2-imx219-cam1.dtbo \
	radxa-cm3-rpi-cm4-camera-v2-imx219-cam0.dtbo \
	radxa-cm3-rpi-cm4-arducam-imx708-cam1.dtbo \
	radxa-cm3-rpi-cm4-arducam-imx708-cam0.dtbo \
	radxa-cm3-rpi-cm4-7inch-touchscreen-disp1.dtbo \
	radxa-cm3-rpi-cm4-7inch-touchscreen-disp0.dtbo \
	radxa-cm3-raspcm4io-pcie2x1.dtbo \
	radxa-cm3-io-sharp-lq133t1jw01-without-hdmi.dtbo \
	radxa-cm3-io-sata2.dtbo \
	radxa-cm3-io-sata1.dtbo \
	radxa-cm3-io-radxa-10p1inch-display.dtbo \
	radxa-cm3-io-pcie2x1.dtbo \
	radxa-cm3-io-okdo-5mp-camera-cam2.dtbo \
	radxa-cm3-io-okdo-5mp-camera-cam1.dtbo \
	radxa-cm3-io-i2c0-hym8563.dtbo \
	radxa-cm3-io-hd101boe9365-display.dtbo \
	radxa-cm3-io-dual-cameras-gc2053.dtbo \
	radxa-cm3-io-dual-cameras-gc2053-gc2093.dtbo \
	radxa-cm3-io-camera-v2-imx219-cam2.dtbo \
	radxa-cm3-io-camera-v2-imx219-cam1.dtbo \
	rock-5a-arducam-imx708-hdr.dtbo \
	rock-5a-arducam-imx708.dtbo \
	rock-5a-arducam-pivariety.dtbo \
	rock-5b-arducam-imx708-hdr.dtbo \
	rock-5b-arducam-imx708.dtbo \
	rock-5b-arducam-pivariety.dtbo \

dtbotxt-$(CONFIG_ARCH_ROCKCHIP) += \
	README.rockchip-overlays

targets += $(dtbo-y) $(dtbotxt-y)

always-y		:= $(dtbo-y) $(dtbotxt-y)
clean-files		:= *.dtbo

