name: Build_Kernel_for_OpenHD_crosscompile

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: debian:bullseye
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: install dependencies
        run: |
          apt-get update
          dpkg --add-architecture arm64
          apt-get update
          apt-get full-upgrade --no-install-recommends -y wget build-essential crossbuild-essential-arm64 gcc-arm-none-eabi git ruby sudo apt-utils python3 python2 python-is-python2 curl debhelper python3-distutils python3-pkg-resources python3-setuptools python3-pyelftools python3-ply python3-git cpio bc flex fakeroot bison rsync kmod swig device-tree-compiler u-boot-tools python2-dev python3-dev libssl-dev uuid-dev libgnutls28-dev libc6:arm64 libssl-dev:arm64
          gem install fpm
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python2
          python2 -m pip install pyelftools
          apt-get install --no-install-recommends -y qemu-user-static binfmt-support

      - name: compile
        run: |
          git clone --depth=1 https://github.com/openhd/RK_Kernel 
          cd RK_Kernel
          wget -q https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
          tar xvf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz  -C /usr/local/
          apt-get -y install gcc-aarch64-linux-gnu device-tree-compiler libncurses5 libncurses5-dev build-essential libssl-dev mtools
          apt-get -y install bc python dosfstools
          cd ..
          mv RK_Kernel kernel
          export PATH="/usr/local/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin:$PATH"
          git clone https://github.com/openhd/build_radxa_sdk build
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          cd build
          chmod +777 -R ../*
          sudo ./pack-kernel.sh -d rockchip_linux_defconfig -r 99 

      # - name: build kernel
      #   run: |
      #     dpkg-buildpackage -a "$(cat debian/arch)" -d -b -nc -uc
      #     ls -a ../
      #     cd .. 
      #     cp *.deb RK_Kernel/
  
      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: "rock5-kernel-openhd"
          path: |
            *.deb
            RK_Kernel/*.deb
          
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "openhd-2-3-evo"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-image*.deb"

      - name: Push header
        id: push_headers
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "openhd-2-3-evo"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-header*.deb"
