name: Release
on: [push]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get revision
        run: |
          VERSION=$(cat VERSION)
          echo "revision=${VERSION#*-}" >> $GITHUB_ENV
          echo "tag_name=${VERSION}" >> $GITHUB_ENV
      - name: Build
        uses: OpenHD/bsp@main
        with:
          target: linux
          edition: rk356x
          revision: ${{ env.revision }}
      - name: debug
        run: |
          ls -a
      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: "rock5-kernel-openhd"
          path: |
            *.deb
            RK_Kernel/*.deb