name: Release
on: [push]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get revision
        run: |
          VERSION=$(cat VERSION)
          echo "revision=${VERSION#*-}" >> $GITHUB_ENV
          echo "tag_name=${VERSION}" >> $GITHUB_ENV

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential qemu-user-static coreutils binfmt-support

      - name: Clone Wifi drivers
        run: |
          sudo apt update
          sudo apt install -y git
          mkdir modules
          cd drivers/net/wireless/
          rm -Rf rtl8812au
          rm -Rf rtl8812bu

      - name: build kernel for rk3566 (zero3w+cm3)
        run: |
          cd bsp
          chmod +x bsp
          ./bsp --long-version -r radxa linux rk356x

      - name: little hack for github uploads
        run: |
          cp -r /home/runner/work/RK_Kernel/RK_Kernel/bsp/*.deb /home/runner/work/RK_Kernel/RK_Kernel/

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: "rock5-kernel-openhd"
          path: |
            *.deb

      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "dev-release"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-image-5.10.160*.deb"

      - name: Push header
        id: push_headers
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "dev-release"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-headers-5.10.160*.deb"
          
      - name: Push libc
        id: push_libc
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "dev-release"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-libc-dev-5.10.160*.deb"