name: Release
on: [push]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get revision
        run: |
          VERSION=$(cat VERSION)
          echo "revision=${VERSION#*-}" >> $GITHUB_ENV
          echo "tag_name=${VERSION}" >> $GITHUB_ENV

      - name: install dependencies
        run: |
          sudo apt-get install --no-install-recommends -y build-essential qemu-user-static coreutils binfmt-support
      
      - name: build kernel
        run: |
          git clone https://github.com/openhd/bsp
          cd bsp
          chmod +x bsp
          ./bsp --long-version -r 1 linux rk356x |& tee buildlog.log
          echo "------------------------------------------------------------"
          ls -a
          echo "------------------------------------------------------------"
          tree
          echo "------------------------------------------------------------"

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: "rock5-kernel-openhd"
          path: |
            *.log
            *.deb
            RK_Kernel/*.log
            RK_Kernel/bsp/*.deb
