name: Release
on: [push]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get revision
        run: |
          VERSION=$(cat VERSION)
          echo "revision=${VERSION#*-}" >> $GITHUB_ENV
          echo "tag_name=${VERSION}" >> $GITHUB_ENV

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get full-upgrade --no-install-recommends -y wget build-essential crossbuild-essential-arm64 gcc-arm-none-eabi git ruby sudo apt-utils python3 curl debhelper python3-distutils python3-pkg-resources python3-setuptools python3-pyelftools python3-ply python3-git cpio bc flex fakeroot bison rsync kmod swig device-tree-compiler u-boot-tools python2-dev python3-dev libssl-dev uuid-dev libgnutls28-dev
          sudo gem install fpm
          sudo apt-get install --no-install-recommends -y qemu-user-static binfmt-support

      - name: build kernel
        run: |
          git clone -b latest https://github.com/openhd/bsp
          cd bsp
          chmod +x bsp
          ./bsp --native-build --long-version -r radxa linux rk356x

      - name: little hack for github uploads
        run: |
          cp -r /home/runner/work/RK_Kernel/RK_Kernel/bsp/*.deb /home/runner/work/RK_Kernel/RK_Kernel/

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: "rock5-kernel-openhd"
          path: |
            *.deb

      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "dev-release"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-image-5.10.160*.deb"

      - name: Push header
        id: push_headers
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "dev-release"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-headers-5.10.160*.deb"
          
      - name: Push libc
        id: push_libc
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "dev-release"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "linux-libc-dev-5.10.160*.deb"